name: Question
description: Any question related to nvim_training
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question here.
      placeholder: A clear and concise description of what you want to know.
    validations:
      required: true
